[package]
name = "auditalogs"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
lapin = "2.5.0"
futures-lite = "2.5.0"
uuid = { version = '1.11.0', features = [
  "v4",
  "fast-rng",
  "macro-diagnostics",
] }
