[package]
name = "auditalogs"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
tokio = { version = "1", features = ["full"] }
lapin = "2.5.0"
futures-lite = "2.5.0"
serde = "1.0.215"
serde_json = "1.0.133"
elasticsearch = "8.16.0-alpha.1"
