services:
  besu:
    image: hyperledger/besu:25.2.2
    restart: unless-stopped
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - besudata:/var/lib/besu
    command: >
      --network=dev
      --rpc-http-cors-origins="all"
      --rpc-http-enabled
      --metrics-enabled
      --host-allowlist="*"
      --rpc-http-api=ETH,NET,WEB3,DEBUG,TXPOOL
      --rpc-ws-enabled
      --data-path=/var/lib/besu
      --rpc-ws-api=ETH,NET,WEB3
      --miner-enabled
      --miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
      --logging=INFO
      --rpc-http-max-active-connections=100000
      --min-gas-price=0


volumes:
  besudata:
