[package]
name = "audita-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
elasticsearch = "8.16.0-alpha.1"
serde = "1.0.215"
serde_json = "1.0.133"
sha2 = "0.10.8"
alloy = { version = "0.6.4", features = ["full"] }
