#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/solc@0.8.30/node_modules/solc/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/solc@0.8.30/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/node_modules:/home/segfault/Github/audita/~/.local/share/node_modules:/home/segfault/Github/audita/~/.local/node_modules:/home/segfault/Github/audita/~/node_modules:/home/segfault/Github/audita/node_modules:/home/segfault/Github/node_modules:/home/segfault/node_modules:/home/node_modules:/node_modules:~/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/solc@0.8.30/node_modules/solc/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/solc@0.8.30/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/.pnpm/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/5/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/global/node_modules:/home/segfault/Github/audita/~/.local/share/pnpm/node_modules:/home/segfault/Github/audita/~/.local/share/node_modules:/home/segfault/Github/audita/~/.local/node_modules:/home/segfault/Github/audita/~/node_modules:/home/segfault/Github/audita/node_modules:/home/segfault/Github/node_modules:/home/segfault/node_modules:/home/node_modules:/node_modules:~/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/.pnpm/solc@0.8.30/node_modules/solc/solc.js" "$@"
else
  exec node  "$basedir/global/5/.pnpm/solc@0.8.30/node_modules/solc/solc.js" "$@"
fi
