services:
  auditaserver:
    image: ghcr.io/luizfelmach/auditaserver:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./auditaserver/:/etc/auditaserver:ro
      - auditalogs:/var/log/

volumes:
  auditalogs:
    external: true
