services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafanadata:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    network_mode: host
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./loki:/etc/loki/

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    network_mode: host
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail:/etc/promtail/

volumes:
  grafanadata:
