host = "0.0.0.0"
port = 8888
name = "worker"
queue_size = 2048
batch_size = 500
threads = 12

[ethereum]
url = "http://localhost:8545"
contract = ""
primary_key = ""
disable = false

[elastic]
url = "http://localhost:9200"
username = "elastic"
password = "changeme"
disable = false
