global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "besu"
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9545"]

  - job_name: "auditaserver"
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:8080"]
