[package]
name = "audita-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.29.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
rand = "0.8.5"
chrono = "0.4"
