name: Auto Tag
on:
  push:
    branches: [main]
    paths: ["Cargo.toml"]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Create tag
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "v$VERSION"
          git push origin "v$VERSION"
