name: Build and Publish audita

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: ghcr.io/luizfelmach/audita

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build binary
        run: cargo build --release

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audita-binary
          path: target/release/audita

  docker:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ github.ref_name }} .
          docker tag $IMAGE_NAME:${{ github.ref_name }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.ref_name }}
          docker push $IMAGE_NAME:latest
